### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by hilfing**

### CODE REVIEW

**Comment by hilfing** [comment]
PLs accept
BTW, my mom forced me to stop discord. i may never return

**Comment by SurajKumar997** [comment]
okk

**Comment by hilfing** [comment]
Thx, bye. i will miss you

**Comment by SurajKumar997** [comment]
miss you too😥

**Comment by SurajKumar997** [comment]
can you give me your bitcoins bal plz and make me your fac admin plz

**Comment by hilfing** [comment]
which faction

**Comment by SurajKumar997** [comment]
bcoins

**Comment by hilfing** [comment]
i have deleted my discord account

**Comment by SurajKumar997** [comment]
arre yaar

**Comment by hilfing** [comment]
lol, my mom forced me too
my acc is permanently deleted
cause i was being distracted from studies

**Comment by SurajKumar997** [comment]
ohhkkk

**Comment by hilfing** [comment]
bye bye

**Pull request merged**
